### ISSUE TITLE
Namespace everything under /posts/:id

### ISSUE THREAD

**Issue by jjaffeux** [discourse/discourse-reactions#4]
@lis2 

What would you think of having every routes under this format:

```
GET /discourse-reactions/posts/1/custom-reactions # index
GET /discourse-reactions/posts/1/custom-reactions/:reaction_id # show
DELETE /discourse-reactions/posts/1/custom-reactions/:reaction_id # destroy
POST /discourse-reactions/posts/1/custom-reactions/:reaction_id # create
PUT /discourse-reactions/posts/1/custom-reactions/:reaction_id/toggle # would create or destroy for you
```

- I don't like having post_id inside each body requests, feels wrong to me
- I don't like having the toggle logic client side

**Comment by lis2** [comment]
@jjaffeux sounds good to me! I will take care of namespace and toggle tomorrow :)

**Comment by jjaffeux** [comment]
> @jjaffeux sounds good to me! I will take care of namespace and toggle tomorrow :) 

Im not actually sure we need create/delete if we do this. Up to you.
